name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Install dependencies
        uses: bahmutov/npm-install@v1
      
      - name: Build project
        run: npm run build

      - name: Build project
        run: npm run build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: production-files
          path: ./dist

      - name: Deploy to GitHub Pages
        run: |
          git init
          git config --global user.email ariel.betti@gmail.com
          git config --global user.name arielbetti
          git status
          git remote add origin https://${{secrets.TOKEN}}@github.com/ArielBetti/react-dynamic-dictionary
          git checkout -b release
          git add .
          git commit -m "ci: publish release in github pages"
          git push origin release
